export const MAIN_API = process.env.NEXT_PUBLIC_BACKEND_URL

export const GET_BRANDS = MAIN_API + '/api/brands'
export const GET_LOCATIONS = MAIN_API + '/api/locations'
export const GET_CARS_BY_TYPE = MAIN_API + '/api/car-by-type'
export const GET_CARS = MAIN_API + '/api/cars'
export const GET_CAR = MAIN_API + '/api/car'
export const GET_DISCOUNT = MAIN_API + '/api/car'
export const CHECK_DISCOINT_PROXY = '/api/proxy/discount'
export const POST_BOOKING_PROXY = '/api/proxy/booking'
export const CONTACT_PROXY = '/api/proxy/contact'
export const CONTACT =MAIN_API + '/api/contact'
export const POST_BOOKING = MAIN_API + '/api/booking'
export const GET_BLOGS = MAIN_API + '/api/blogs'
export const GET_BLOG = MAIN_API + '/api/blogs'
export const GET_ABOUT = MAIN_API + '/api/about'
export const GET_FAQS = MAIN_API + '/api/faq'
export const LOGIN = MAIN_API + '/api/login'
export const GET_COMPANY = MAIN_API + '/api/company'
export const GET_PRIVACY = MAIN_API + '/api/privacy-policy'
export const GET_TERMS= MAIN_API + '/api/terms-and-conditions'

